[package]
name = "nyaa_tracker"
version = "0.1.0"
authors = ["VanillaBrooks <brookskarlik@gmail.com>"]
edition = "2018"
reqwest = "0.9.8"

[dependencies]
reqwest = "0.9.9"
hashbrown = "0.3.0"
regex = "1.1.6"

#![allow(dead_code)]
#![allow(unused_code)]
#![deny(warnings)]
#![allow(unused_imports)]
#[allow(dead_code)]
#[allow(unused_attributes)]
#![feature(try_trait)]
