[package]
name = "nyaa_tracker"
version = "0.1.0"
authors = ["VanillaBrooks <brookskarlik@gmail.com>"]
edition = "2018"
reqwest = "0.9.8"

[dependencies]
reqwest = "0.9.9"
hashbrown = "0.3.0"
regex = "1.1.6"


serde_bencode = "0.2.0"
serde_derive = "1.0.91"
serde_bytes = "0.11.1"
serde = "1.0.91"

rss = "1.7.0"